version: 0.2
env:
  parameter-store:
    spring_boot_docker_ecs_url: "pring-boot-docker-ecs-url"
phases:
  install:
    runtime-versions:
      java: openjdk11
      docker: 18
    commands:
      - echo install step...
  pre_build:
    commands:
      - echo logging in to AWS ECR...
      - $(aws ecr get-login --no-include-email --region ap-southeast-2)
  build:
    commands:
      - export MAVEN_CONFIG=''
      - echo build Docker image on `date`
      - ./mvnw install dockerfile:build dockerfile:push -Ddocker-image-ecr-repo=$spring_boot_docker_ecs_url
cache:
  paths:
    - '/root/.m2/**/*'